---
- name: AWS configuration
  hosts: localhost
  vars_files:
    - aws_creds
  tasks:
    - name: AWS config access key
      shell: |
        aws configure set aws_access_key_id {{ AWS_ACCESS_KEY_ID }} --profile default 
        aws configure set aws_secret_access_key {{ AWS_SECRET_ACCESS_KEY }} --profile default 
        aws configure set aws_default_region {{ AWS_DEFAULT_REGION }} --profile default
      register: output
    - debug:
        var: output

