---
- name: EC2 instance creation
  hosts: localhost
  ignore_errors: true
  vars:   
    - image_id: ami-0d0ad8bb301edb745
  tasks: 
    - name: image name
      amazon.aws.ec2_ami_info:
        image_ids: '{{ image_id }}'
      register: ami_availability_check

    - name:
      debug:
        msg: "{{ ami_availability_check['images'][0]['state'] }}"
