---
- name:
  hosts: localhost
  tasks:
    - name: start instance
      amazon.aws.ec2_instance:
        state: stopped
        filters:
          tag:Name: "TestVM"
    - name: wait till instance started running
      amazon.aws.ec2_instance_info:
        filters:
          tag:Name: "TestVM"
      register: state_out
      until: state_out.instances[0]['state']['name'] ==  'stopped'
      retries: 10
      delay: 15

    - name: state
      debug:
        msg: "{{ state_out.instances[0]['state']['name'] }}"
