---
- name:
  hosts: localhost
  tasks:
    - name: wait till instance started running
      amazon.aws.ec2_instance_info:
        filters:
          tag:Name: "TestVM"
      register: state_out

    - name: state
      debug: 
        var: state_out
        #msg: "{{ state_outinstances['state'][0]['name'] }}"

          #- name: wait
          #until: "{{ state_out['instances']['images'][0]['state'] }} == 'stopped'"
          #retries: 10
          #delay: 15

